version: '3'
services:

  nginx:
    build: ./nginx/
    ports:
    - "80:80"
    volumes:
      - ./nginx/public:/data/www
    depends_on:
      - "api"

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/frontend/app
      - ./nginx/public:/frontend/public

    working_dir: /frontend/
    command: npm run build

  api:
    build: ./api/

    volumes:
    - ./api:/app
    - /media/siweb:/media
    - /tmp/siweb:/tmp/siweb

    working_dir: /app/
    command: uwsgi --ini uwsgi.ini

    environment:
      BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    depends_on:
      - "db"

  redis:
    image: redis
    ports:
    - "6379:6379"

  db:
    image: postgres
    restart: always
    expose:
    - "5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: "test"


  celery_worker:
    build: ./api/
    working_dir: /app
    command: celery worker -A tasks --loglevel INFO

    volumes:
      - ./api/app:/app
      - /media/siweb:/media
      - /tmp/siweb:/tmp/siweb

    environment:
      BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

    depends_on:
      - "db"
      - "redis"
      - "mongo"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
